apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            key: external-secrets-k8s-creds.json
            name: gcp-store-creds
            namespace: external-secrets
      projectID: id-to-project
