apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
  - robin-cli-pod.yaml
  - robin-snapshotclass.yaml
  - robin-storage-resources.yaml

