apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: robin-vm-repl-3-block-immediate
parameters:
  faultdomain: host
  replication: "3"
  blocksize: "512"
provisioner: robin
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: robin-vm-repl-3-block-immediate
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: robin-vm-repl-2-block-immediate
parameters:
  faultdomain: host
  replication: "2"
  blocksize: "512"
provisioner: robin
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: robin-vm-repl-2-block-immediate
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: robin-repl-2
parameters:
  replication: "2"
provisioner: robin
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: robin-repl-2
spec: {}
